# This file was generated by GoReleaser. DO NOT EDIT.
cask "fritz-tls" do
  version "0.28.0"

  on_macos do
    on_intel do
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_darwin_amd64.zip"
      sha256 "34b5a80194eb2abe273bb6912c6a0950b91ac4ef9db92440f637dc6e3c2c0281"
    end
    on_arm do
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_darwin_arm64.zip"
      sha256 "d28b5b4369e805d982a16a02bdab3ef3e6e35e7d6ba0b8a33eebaf7b664c9203"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_linux_amd64.tar.gz"
      sha256 "29076395b4f35fbb0b82430993fa4641a8c1bf50ef51e9369ba319ab50d455f8"
    end
    on_arm do
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_linux_arm64.tar.gz"
      sha256 "0b6f85eb70b41d767f8422fb6a7cee23b6afd51168c19634adfbe70451fdd308"
    end
  end

  name "fritz-tls"
  desc "Automate TLS certificate installation for AVM FRITZ!Box"
  homepage "https://github.com/tisba/fritz-tls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fritz-tls"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fritz-tls"]
    end
  end

  # No zap stanza required

end
