# This file was generated by GoReleaser. DO NOT EDIT.
cask "fritz-tls" do
  desc "Automate TLS certificate installation for AVM FRITZ!Box"
  homepage "https://github.com/tisba/fritz-tls"
  version "0.24.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fritz-tls"

  on_macos do
    on_intel do
      url "https://github.com/tisba/fritz-tls/releases/download/v0.24.0/fritz-tls_0.24.0_darwin_amd64.zip"
      sha256 "3311ff8c20af9b64a4ca418766909f1472c4a5cb8eb748eaeefa8313c82c3f32"
    end
    on_arm do
      url "https://github.com/tisba/fritz-tls/releases/download/v0.24.0/fritz-tls_0.24.0_darwin_arm64.zip"
      sha256 "6cb418ace29fc1890edd1dfad5837527479e8ab4cb6ccbc3e0bda306601451d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tisba/fritz-tls/releases/download/v0.24.0/fritz-tls_0.24.0_linux_amd64.tar.gz"
      sha256 "7af33ba515d2bed27873ee45b857f51222f2498fc77228e79abb7d0a5c851ef8"
    end
    on_arm do
      url "https://github.com/tisba/fritz-tls/releases/download/v0.24.0/fritz-tls_0.24.0_linux_arm64.tar.gz"
      sha256 "345671eb7d3c54a4a86430d28d452e7af4d46ca943de4f8f25921201c89b5bf5"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fritz-tls"]
    end
  end

  # No zap stanza required
end
