# This file was generated by GoReleaser. DO NOT EDIT.
cask "fritz-tls" do
  version "0.29.0"

  on_macos do
    on_arm do
      sha256 "3b6da291753677cc7c477d09e36fa75988d097e5494f6c2414e96b056010390a"
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_darwin_arm64.zip"
    end
    on_intel do
      sha256 "de31cca97200de49a78882e0d8bc83e53c6412554fdb0c6a7d1ec71f6b3f89e4"
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "272e74b4c4c924190b25b5eed667a66f15d2125d020aa7d4bde3638168f3b1e8"
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1436e8d06c7f683cb0ac69f2709b095c7be556044ce34b3d3ea2e583cd5281f"
      url "https://github.com/tisba/fritz-tls/releases/download/v#{version}/fritz-tls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fritz-tls"
  desc "Automate TLS certificate installation for AVM FRITZ!Box"
  homepage "https://github.com/tisba/fritz-tls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fritz-tls"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fritz-tls"]
    end
  end

  # No zap stanza required
end
