# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FritzTls < Formula
  desc "Automate TLS certificate installation for AVM FRITZ!Box"
  homepage "https://github.com/tisba/fritz-tls"
  version "0.9.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tisba/fritz-tls/releases/download/v0.9.0/fritz-tls_0.9.0_darwin_x86_64.zip"
      sha256 "1fbcf4002ef8576f9a644016ebbfaacc9e48a817f8025220ede69612ad63b2cc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tisba/fritz-tls/releases/download/v0.9.0/fritz-tls_0.9.0_darwin_arm64.zip"
      sha256 "84fe979fb36510dcc165b6cbe8b4b4a39ff72569cd4019a9a8bc0e87045789ad"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tisba/fritz-tls/releases/download/v0.9.0/fritz-tls_0.9.0_linux_x86_64.tar.gz"
      sha256 "5d241f3222c1e7cb7879b38ac488fb912a2ffaa400c19276ba84d842dce6a23e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tisba/fritz-tls/releases/download/v0.9.0/fritz-tls_0.9.0_linux_arm64.tar.gz"
      sha256 "4cb88d318d2bdcf92cb9f60a0a03072591f7aacc2cb247a7baaa9d42fc1a5189"
    end
  end

  def install
    bin.install "fritz-tls"
  end
end
